title: FV Tech Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://fv-tech.ghp.projnull.eu

favicon_ico: assets/icon.png

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

nav_enabled: true

nav_error_report: true

color_scheme: dark

permalink: pretty



callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue

aux_links:
  Website (Currenty Private): https://projnull.eu/project/fv-tech
