title: FV Tech Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://fv-tech.ghp.projnull.eu

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

nav_enabled: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
